### PR TITLE
Add Ghostdown for live editing. Add ability to add more categories 'fold...

### PR DESCRIPTION
**Pull request by matthiassb**
This PR includes changes that allow for live editing of the markdown, save changes to the markdown page, deleting a page, adding a new page and adding a new category from the web interface

### CODE REVIEW

**Comment by ryanlelek** [comment]
Thanks for the PR @matthiassb.
You've done a lot of work, so I'll need to look at this in-depth before merging.
Will update with status changes

**Comment by ryanlelek** [comment]
Reviewing this now

**Comment by ryanlelek** [comment]
This all worked on the first try, excellent PR.
Thanks for this PR @matthiassb, lots of people were wanting an online editor including myself.

**Comment by matthiassb** [comment]
Cool! Glad to be of help :)

**Comment by ryanlelek** [comment]
@matthiassb, I'm in the process of moving dependencies like jQuery, Bootstrap, and such to Bower to keep things clean and audit-able.

When searching for "ghostdown" on Bower, I didn't find any results. I do see that your Ghostdown files contain CodeMirror, so could you provide some more insight on which pieces are reusable so I can move them to Bower?

I did a quick Google search for "Ghostdown" and found this, but I wanted to check with you since you added Ghostdown to the project. https://github.com/timsayshey/Ghost-Markdown-Editor

**Pull request merged**
