### PR TITLE
More core integrations

### PR DESCRIPTION
**Pull request by Sparticuz**
Was able to remove the package.json in the core integration by moving all the scripts to the main package.json. Fixed the scripts and tests. Also fixed travis.

### CODE REVIEW

**Comment by ryanlelek** [comment]
Lots of updates in this, will do my best to address
- Moving away from Babel
- `travis.yml` was pulled in from Raneto Core (with Gilbert's help/guidance) before I looked at PRs. Didn't see this until it was imported

So if we strip that out, it end up being an `npm lint` and a dir rename. will merge if you do, up to you

**Comment by Sparticuz** [comment]
Don't we need babel to transpile the core? I wasn't able to transpile until I moved that file from the other repo.

I'll pull out the travis.yml, I was just getting annoyed with it failing, lol.

**Comment by ryanlelek** [comment]
Yes on babel, but with minimal edits, I was planning to find/replace `yamljs` with `js-yaml` and the one other method on the already transpiled code. That's the simple/hard way.

But, hold off on babel coming into the main `package.json` for the moment

**Comment by Sparticuz** [comment]
side note on travis, we state in package.json that node must be 4+, but in travis, we're testing on .10 and .12. The tests would go quicker if those two were removed.

**Comment by Sparticuz** [comment]
OK, I'm pleased with this PR, let me know if you want me to change anything.

**Comment by ryanlelek** [comment]
Good, thank you

**Comment by ryanlelek** [comment]
Also, I added a `dev` branch just now so let's go future PRs against that to keep master for releases

Will release tonight

**Comment by Sparticuz** [comment]
Yep, I saw. Thanks!

**Pull request merged**
