### PR TITLE
build_nested_pages() support windows directory separator

### PR DESCRIPTION
**Pull request by denisvmedia**
This pull request brings respect for windows directory separator char. Actually, I'm aware that there are more such places. Probably, I will provide further PRs, if you don't mind :)

### CODE REVIEW

**Comment by ryanlelek** [comment]
Thanks, we always appreciate cross-platform updates

I'm not on Windows frequently and Travis doesn't have an option for a Windows OS (per https://docs.travis-ci.com/user/multi-os/). If you have suggestions on how we can add Windows support to the pipeline, that'd be appreciated

**Comment by ryanlelek** [comment]
Remerged with commit 4f8ab9e86286a

**Comment by denisvmedia** [comment]
@ryanlelek hi, I don't see this change in master nor in dev. Is it done intentionally?

**Comment by ryanlelek** [comment]
Fixed in [95a3b8ac](https://github.com/gilbitron/Raneto/commit/95a3b8ac150556056370c475731d0cc6de441f60)

**Pull request merged**
