### PR TITLE
Adds Docker deployment support to Raneto

### PR DESCRIPTION
**Pull request by prologic**
This lets you simply:

```#!bash
docker build -t raneto .
docker run -d -e VIRTUALHOST=kb.mydomain.com -e PORT=3000 raneto
```

The configeration above is only an example and uses
[autodock-paas](https://github.com/prologic/autodock-paas)

Otherwise just: `docker run -d -p 3000:3000 raneto` and hit http://<ip_of_docker_host>:3000/

### CODE REVIEW

**Comment by ryanlelek** [comment]
Thank you for this,

In testing, I get it running with the following commands, ports appear to be forwarded, but localhost:3000 doesn't respond.
Can you help diagnose so I can verify and merge this in?
```
$ docker-machine create --driver virtualbox dev
$ eval "$(docker-machine env dev)"
$ docker build -t raneto .
$ docker run -d -p 3000 raneto
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                     NAMES
a66505f299c1        raneto              "npm start"         34 seconds ago      Up 21 seconds       0.0.0.0:32768->3000/tcp   thirsty_hoover
````

**Comment by prologic** [comment]
Oh you're on OS X with a virtualized/remote Docker Engine :) You'll have to use http://a.b.c.d:3000/ where a.b.c.d is the remote ip. I think `docker-machine ip <machine_name>` will give you that.

**Comment by ryanlelek** [comment]
Ok, got the IP with your exact command.
Still empty reply from server though :/

**Comment by prologic** [comment]
Oh I'm sorry! I'm so used to my autodock-pass infrastructure :)

Try: `docker run -d -p 3000:3000 raneto`

Looks like I fubared that up!

**Comment by ryanlelek** [comment]
Bingo, thanks for the quick assistance.
I should probably spend some time figuring out what I'm doing :)
If you'd like, update the docs as you see fit for the regular Docker and your autodock version

Merging

**Comment by prologic** [comment]
Okay sure! I'll do that with a follow up PR. I've already found Raneto quite useful and very easy to setup! The only feature it's missing is protected views; my intention was to spin up a private Raneto instance for internal use only via authenticated viewers :)

**Comment by ryanlelek** [comment]
We might have that protected internal-only feature already, with config.js
Or does that not accomplish what you're looking to do?

Here's the combo and I'll update documentation to make it easier because it is confusing.
```
// Set to true to enable the web editor
allow_editing : true,

// Set to true to enable HTTP Basic Authentication
authentication : true,
credentials    : {
    username : 'admin',
    password : 'password'
}
```

**Comment by prologic** [comment]
I did this but it still lets unauthenticated users view the content; I'll
try again in an incognito session in case it was some silly cache thing :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ryanlelek** [comment]
Ah yes, you're right.
Please see #106 and #112

**Comment by prologic** [comment]
Ahhh thanks :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request merged**
