### PR TITLE
Add ability to authenticate only for edtiing

### PR DESCRIPTION
**Pull request by alexspeller**
I wanted read only knowledge base but one that admins can edit.

### CODE REVIEW

**Comment by ryanlelek** [comment]
Thanks for the PR.
Could this already be accomplished in the current project with
```
config.allow_editing = true
config.authentication = true
```
or am I misunderstanding?

**Comment by alexspeller** [comment]
No, that would authenticate all requests, even to view only.

This PR allows public readable knowledgebase, that authenticated users can edit.

**Comment by alexspeller** [comment]
Wait, I'm not sure about that any more. I can't remember exactly as it was over a month ago, but the use case I was needing was not fully supported by that config. Maybe it was just showing the edit button if there was not a user logged in? Not entirely sure any more, I'll have to look into it in detail

**Comment by ryanlelek** [comment]
I understand, there has been a lot of confusion around the various "modes" of Raneto (I'm confused myself!). I'll make updating docs a priority.

**Comment by ryanlelek** [comment]
Integrated, and is now the default. Thank you!

**Pull request merged**
