### PR TITLE
Add category homepage (instead of redirecting to 404)

### LINKED ISSUE #45: Link to category url to first file url, rather than 404.
If I have a category called "posts" and the first file in that is "my-first-post", 

Set it up so that if I try to access /posts it redirects me to /posts/my-first-post, tather than a 404 page.

### PR DESCRIPTION
**Pull request by caseyjhol**
Fixes #45.

@ryanlelek @gilbitron

### CODE REVIEW

**Comment by caseyjhol** [comment]
Not sure why the tests are failing. They're all passing when I run them locally.

**Comment by ryanlelek** [comment]
Thanks for the PR and merging to `dev` branch.
According to Travis, this is where things are failing:
```
  1) #getCategoryPage()
       returns an array of values for a given category:
     AssertionError: Target cannot be null or undefined.
      at Context.<anonymous> (test/raneto-core.test.js:264:28)
```
Looks like the test is providing an unexpected undefined/empty array.
Keep in mind, we're intending to support non-ES6 code to increase the available options for deployment (e.g. Ubuntu defaults to v6.x.x of Node in the default package repos).
ES6 code may be causing some compatibility issues

Note, the above error was for Node v8.x.x which should have full ES6 support

Please look into that stack trace and report back on how we can help you troubleshoot :)

**Comment by caseyjhol** [comment]
I rebased and updated Node to 8.4.0 and NPM to 5.3.0 (to match Travis) and all of my tests are still passing.

**Comment by caseyjhol** [comment]
@ryanlelek Got it figured out! I wasn't taking into account the different ways paths are normalized in Windows vs Linux.

**Comment by caseyjhol** [comment]
@ryanlelek Any comments on this?

**Comment by Bart274** [comment]
This one would be a nice addition to Raneto :-)

**Comment by caseyjhol** [comment]
@ryanlelek Any reason why this was closed?

**Comment by caseyjhol** [comment]
@ryanlelek ?

**Comment by ryanlelek** [comment]
Probably the `dev` branch. Resubmit on `master` and I'll take a look

**Pull request closed without merging**
