### PR TITLE
Switch to eslint

### PR DESCRIPTION
**Pull request by Sparticuz**
Move from jshint to eslint. (more powerful)
Lint spacing on translations
Lint app

### CODE REVIEW

**Comment by ryanlelek** [comment]
Agree, and looks good at first glance.
Due to size, will review this weekend (added time to calendar to ensure it gets completed)

**Comment by ryanlelek** [comment]
I like the changes @Sparticuz.
During the final testing, there was an issue.

When running npm install, this is my output:
- Am I missing something obvious?
- Looks to be a babel/eslint conflict and I'm completely ok with dropping babel

```
> raneto@0.11.0 compile ~/Raneto
> babel app/core/src --out-dir app/core/lib

app/core/src/raneto.js -> app/core/lib/raneto.js
npm ERR! Darwin 15.6.0
npm ERR! argv "~/.nodebrew/node/v4.5.0/bin/node" "~/.nodebrew/current/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-promise@2.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-standard@6.2.1 wants eslint-plugin-promise@>=3.3.0




node --version
v4.5.0
```

**Comment by Sparticuz** [comment]
I don't think it's babel, I think the eslint deps might just need to be upgraded. I'm moving this weekend, so I won't have a lot of access to the internet, so I won't be able to fix this until after Thanksgiving in America.

**Comment by ryanlelek** [comment]
Agree with move to ESLint.
Will merge as-is (I'll resolve conflicts) and may edit the rules going forward after further review.
At least we'll get this marked as completed :)

**Comment by ryanlelek** [comment]
Looks like the patch is non-existent because the fork was deleted (no big deal, this was open a long time). I'll rebuild as best I can and mark you as contributor @Sparticuz.

**Comment by ryanlelek** [comment]
Commit `eb29830`
Link: https://github.com/gilbitron/Raneto/commit/eb298308b4545deaaf056ce8370565c3ac69596b

**Pull request closed without merging**
