### PR TITLE
Added ability to edit meta information for md files

### PR DESCRIPTION
**Pull request by draptik**
This adds ability to edit meta information for md files (see issue #97 ).

selection_018

Let me know if there is anything I should improve.

### CODE REVIEW

**Comment by ryanlelek** [comment]
Looks good and worked for me on the first attempt.
Merged! Thanks for the contribution.

Two additional improvements if you're up for them:

- We're going to be moving towards testing functionality and style for contributions very soon. Please fix the minor warnings after running `make test`. I'll also update the main "Contribution" docs to reflect this move towards testing.

- let's find a way to refactor out the nested function definition as seen below:
```
 function create_content(body) {
    function create_meta_info(meta_title, meta_description, meta_sort) {}
    // ...
}
```

**Comment by draptik** [comment]
@ryanlelek (1) `make test` now passes without warnings. (2) Which pattern should be applied for refactoring the nested functions?

**Comment by ryanlelek** [comment]
You made the `create_meta_info()` excellently, without relying on the scope of `create_content()` or the `body` variable, so instead of defining `create_meta_info()` within `create_content()` we just need to move it to the top of the same file or in a separate file in the `app/functions/` directory. this will help when we do unit tests

**Comment by draptik** [comment]
Thanks for the feedback: I'll move the function `create_meta_info` to a new file in `app/functions`. I'll create a seperate pull request.

**Pull request merged**
