### PR TITLE
Allow passing in translations through the config object

### PR DESCRIPTION
**Pull request by jdurand**

### CODE REVIEW

**Comment by yaruson** [comment]
As far as I understand, `config.locale` keeps language code, while `config.lang` originally stores actual translation strings. Why not put translations into `./translations/` so they picked from file?

**Comment by jdurand** [comment]
I'm using Raneto as an external dependency and the translations under `app/translations` aren't picked up, so all translated strings end up blank.
So far, this is only way I was able to have translations working.

**Comment by yaruson** [comment]
Sorry @jdurand I didn't think about this use case. As for me, the approach is OK, but of course it should be documented after merging into production.

**Comment by ryanlelek** [comment]
Thanks, this is a great solution.
As we move from an all-in-one app to a hybrid (all-in-one and require-able), these PRs and discussions are appreciated

**Pull request merged**
